const fs = require('fs');
const path = require('path');

// Path untuk menyimpan konfigurasi Nginx yang di-generate
// Pada server Linux: /etc/nginx/panel-conf.d/
// Untuk development di Windows: ./nginx-configs/
const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || path.join(__dirname, '..', 'nginx-configs');

// Pastikan folder ada
if (!fs.existsSync(NGINX_CONF_DIR)) {
  fs.mkdirSync(NGINX_CONF_DIR, { recursive: true });
}

/**
 * Template konfigurasi Nginx untuk HTTP proxy
 */
function generateHttpConfig(proxy) {
  return `# Auto-generated by Nginx Proxy Panel
# Domain: ${proxy.domain_name}
# Created: ${proxy.created_at}

server {
    listen 80;
    server_name ${proxy.domain_name};

    # Logging
    access_log /var/log/nginx/${proxy.domain_name}.access.log;
    error_log /var/log/nginx/${proxy.domain_name}.error.log;

    location / {
        proxy_pass http://${proxy.target_ip}:${proxy.target_port};
        proxy_http_version 1.1;

        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
`;
}

/**
 * Template konfigurasi Nginx untuk HTTPS proxy (SSL)
 */
function generateHttpsConfig(proxy) {
  return `# Auto-generated by Nginx Proxy Panel
# Domain: ${proxy.domain_name}
# Created: ${proxy.created_at}
# SSL: Enabled

server {
    listen 80;
    server_name ${proxy.domain_name};
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${proxy.domain_name};

    # SSL Certificate
    ssl_certificate /etc/letsencrypt/live/${proxy.domain_name}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${proxy.domain_name}/privkey.pem;

    # SSL Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Logging
    access_log /var/log/nginx/${proxy.domain_name}.access.log;
    error_log /var/log/nginx/${proxy.domain_name}.error.log;

    location / {
        proxy_pass http://${proxy.target_ip}:${proxy.target_port};
        proxy_http_version 1.1;

        # Standard Proxy Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Host $host;

        proxy_redirect off;
        proxy_buffering off;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 90s;
        proxy_send_timeout 90s;
        proxy_read_timeout 90s;
    }
}
`;
}

/**
 * Generate dan tulis file konfigurasi Nginx
 */
function generateConfig(proxy) {
  let useSsl = Boolean(proxy.ssl_enabled);

  // Jika di Linux, pastikan sertifikat Let's Encrypt benar-benar ada di disk
  if (useSsl && process.platform === 'linux') {
    const certPath = `/etc/letsencrypt/live/${proxy.domain_name}/fullchain.pem`;
    const keyPath = `/etc/letsencrypt/live/${proxy.domain_name}/privkey.pem`;
    if (!fs.existsSync(certPath) || !fs.existsSync(keyPath)) {
      console.warn(`⚠️  File sertifikat SSL belum ditemukan untuk ${proxy.domain_name}. Tetap gunakan konfigurasi HTTP.`);
      useSsl = false;
    }
  }

  const config = useSsl ? generateHttpsConfig(proxy) : generateHttpConfig(proxy);
  const filename = `${proxy.domain_name}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);

  fs.writeFileSync(filepath, config, 'utf-8');
  console.log(`📝 Config generated: ${filepath}`);

  return { filepath, filename, config };
}

/**
 * Hapus file konfigurasi Nginx
 */
function removeConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);

  if (fs.existsSync(filepath)) {
    fs.unlinkSync(filepath);
    console.log(`🗑️  Config removed: ${filepath}`);
    return true;
  }
  return false;
}

/**
 * Nonaktifkan config (rename dengan suffix .disabled)
 */
function disableConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);
  const disabledPath = filepath + '.disabled';

  if (fs.existsSync(filepath)) {
    fs.renameSync(filepath, disabledPath);
    console.log(`⏸️  Config disabled: ${domainName}`);
    return true;
  }
  return false;
}

/**
 * Aktifkan kembali config (hapus suffix .disabled)
 */
function enableConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);
  const disabledPath = filepath + '.disabled';

  if (fs.existsSync(disabledPath)) {
    fs.renameSync(disabledPath, filepath);
    console.log(`▶️  Config enabled: ${domainName}`);
    return true;
  }
  return false;
}

/**
 * Cek apakah file config ada
 */
function configExists(domainName) {
  const filepath = path.join(NGINX_CONF_DIR, `${domainName}.conf`);
  return fs.existsSync(filepath);
}

module.exports = {
  generateConfig,
  removeConfig,
  disableConfig,
  enableConfig,
  configExists,
  NGINX_CONF_DIR
};
