const fs = require('fs');
const path = require('path');

// Path untuk menyimpan konfigurasi Nginx yang di-generate
// Pada server Linux: /etc/nginx/panel-conf.d/
// Untuk development di Windows: ./nginx-configs/
const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR || path.join(__dirname, '..', 'nginx-configs');

// Pastikan folder ada
if (!fs.existsSync(NGINX_CONF_DIR)) {
  fs.mkdirSync(NGINX_CONF_DIR, { recursive: true });
}

/**
 * Helper untuk menyisipkan direktif ModSecurity
 */
function getModSecDirectives(wafMode) {
  if (wafMode === 'on') {
    return `
    # ModSecurity Web Application Firewall (WAF) - Active Enforcement
    # Optimized: Nonaktifkan Response Body buffering agar streaming & TTFB super cepat
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;
    modsecurity_rules 'SecRuleEngine On; SecResponseBodyAccess Off;';
`;
  } else if (wafMode === 'detection') {
    return `
    # ModSecurity Web Application Firewall (WAF) - Detection Only (Audit Log)
    # Optimized: Nonaktifkan Response Body buffering agar streaming & TTFB super cepat
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;
    modsecurity_rules 'SecRuleEngine DetectionOnly; SecResponseBodyAccess Off;';
`;
  }
  return `
    # ModSecurity Web Application Firewall (WAF) - Disabled
    modsecurity off;
`;
}

/**
 * Helper untuk menyusun identifier upstream yang aman untuk Nginx
 */
function getSafeUpstreamName(domainName) {
  return (domainName || 'backend').toLowerCase().replace(/[^a-z0-9]/g, '_');
}

/**
 * Helper untuk menyusun daftar server_name termasuk alias CNAME (www <-> apex domain)
 */
function getServerNames(domainName) {
  const domain = (domainName || '').trim().toLowerCase();
  const names = [domain];

  // Jika domain diawali www., tambahkan apex domain sebagai alias
  if (domain.startsWith('www.')) {
    const apex = domain.substring(4);
    if (apex && !names.includes(apex)) {
      names.push(apex);
    }
  } else {
    // Jika bukan www (misal: ids.net.id), tambahkan www.ids.net.id sebagai alias
    const www = `www.${domain}`;
    if (!names.includes(www)) {
      names.push(www);
    }
  }

  return names.join(' ');
}

/**
 * Template konfigurasi Nginx untuk HTTP proxy (High Performance)
 */
function generateHttpConfig(proxy) {
  const modSecBlock = getModSecDirectives(proxy.waf_mode);
  const serverNames = getServerNames(proxy.domain_name);
  const upstreamName = `upstream_${getSafeUpstreamName(proxy.domain_name)}`;
  const targetIp = (proxy.target_ip === 'localhost') ? '127.0.0.1' : proxy.target_ip;

  return `# Auto-generated by Nginx Proxy Panel - High Performance HTTP
# Domain: ${proxy.domain_name}
# Server Aliases: ${serverNames}
# Created: ${proxy.created_at || new Date().toISOString()}
# WAF Mode: ${proxy.waf_mode || 'off'}

upstream ${upstreamName} {
    server ${targetIp}:${proxy.target_port} max_fails=3 fail_timeout=10s;
    keepalive 64;
}

server {
    listen 80;
    server_name ${serverNames};
${modSecBlock}
    # Logging
    access_log /var/log/nginx/${proxy.domain_name}.access.log;
    error_log /var/log/nginx/${proxy.domain_name}.error.log warn;

    client_max_body_size 100M;

    # Static Assets Caching & Acceleration (Bypass overhead & browser caching)
    location ~* \\.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf|otf|eot)$ {
        proxy_pass http://${upstreamName};
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        expires 7d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location / {
        proxy_pass http://${upstreamName};
        proxy_http_version 1.1;

        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support & Upstream Keepalive pooling
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # Buffer Optimization untuk High Throughput
        proxy_buffering on;
        proxy_buffers 16 32k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 128k;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }
}
`;
}

/**
 * Template konfigurasi Nginx untuk HTTPS proxy (SSL - High Performance)
 */
function generateHttpsConfig(proxy) {
  const modSecBlock = getModSecDirectives(proxy.waf_mode);
  const serverNames = getServerNames(proxy.domain_name);
  const upstreamName = `upstream_${getSafeUpstreamName(proxy.domain_name)}`;
  const targetIp = (proxy.target_ip === 'localhost') ? '127.0.0.1' : proxy.target_ip;

  return `# Auto-generated by Nginx Proxy Panel - High Performance HTTPS
# Domain: ${proxy.domain_name}
# Server Aliases: ${serverNames}
# Created: ${proxy.created_at || new Date().toISOString()}
# SSL: Enabled
# WAF Mode: ${proxy.waf_mode || 'off'}

upstream ${upstreamName} {
    server ${targetIp}:${proxy.target_port} max_fails=3 fail_timeout=10s;
    keepalive 64;
}

server {
    listen 80;
    server_name ${serverNames};
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${serverNames};
${modSecBlock}
    # SSL Certificate
    ssl_certificate /etc/letsencrypt/live/${proxy.cert_domain || proxy.domain_name}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${proxy.cert_domain || proxy.domain_name}/privkey.pem;

    # SSL Performance & Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # Logging
    access_log /var/log/nginx/${proxy.domain_name}.access.log;
    error_log /var/log/nginx/${proxy.domain_name}.error.log warn;

    client_max_body_size 100M;

    # Static Assets Caching & Acceleration (Bypass sub_filter & log overhead)
    location ~* \\.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf|otf|eot)$ {
        proxy_pass http://${upstreamName};
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        expires 7d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    location / {
        proxy_pass http://${upstreamName};
        proxy_http_version 1.1;

        # Standard Proxy Headers
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Protocol https;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Url-Scheme https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header HTTPS on;

        # WebSocket support & Upstream Keepalive pooling
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # Buffer Optimization untuk Framework Modern (Bun, Node, Vite, React, Vue, Next.js)
        proxy_buffering on;
        proxy_buffers 16 32k;
        proxy_buffer_size 64k;
        proxy_busy_buffers_size 128k;

        # Redirect rewrite agar tidak looping atau kembali ke http
        proxy_redirect http:// https://;
        proxy_cookie_path / "/; Secure; SameSite=None";

        # Header Browser CSP: otomatis ubah semua link aset internal http:// menjadi https://
        add_header Content-Security-Policy "upgrade-insecure-requests" always;

        # Mixed-content rewrite ringan khusus HTML (tidak membebani JSON / API / JS)
        sub_filter 'http://${proxy.domain_name}' 'https://${proxy.domain_name}';
        sub_filter_once off;
        sub_filter_types text/html;

        # Timeouts fleksibel
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }
}
`;
}

/**
 * Generate dan tulis file konfigurasi Nginx
 */
function generateConfig(proxy) {
  let useSsl = Boolean(proxy.ssl_enabled);

  // Jika di Linux, pastikan sertifikat Let's Encrypt benar-benar ada di disk
  if (useSsl && process.platform === 'linux') {
    const clean = (proxy.domain_name || '').trim().toLowerCase();
    const apex = clean.startsWith('www.') ? clean.substring(4) : clean;
    const candidates = [clean, apex, `www.${apex}`];
    let foundLive = null;

    for (const name of candidates) {
      const certPath = `/etc/letsencrypt/live/${name}/fullchain.pem`;
      const keyPath = `/etc/letsencrypt/live/${name}/privkey.pem`;
      if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
        foundLive = name;
        break;
      }
    }

    if (!foundLive) {
      console.warn(`⚠️  File sertifikat SSL belum ditemukan untuk ${proxy.domain_name}. Tetap gunakan konfigurasi HTTP.`);
      useSsl = false;
    } else {
      proxy.cert_domain = foundLive;
    }
  }

  const config = useSsl ? generateHttpsConfig(proxy) : generateHttpConfig(proxy);
  const filename = `${proxy.domain_name}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);

  fs.writeFileSync(filepath, config, 'utf-8');
  console.log(`📝 Config generated: ${filepath}`);

  return { filepath, filename, config };
}

/**
 * Hapus file konfigurasi Nginx
 */
function removeConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);

  if (fs.existsSync(filepath)) {
    fs.unlinkSync(filepath);
    console.log(`🗑️  Config removed: ${filepath}`);
    return true;
  }
  return false;
}

/**
 * Nonaktifkan config (rename dengan suffix .disabled)
 */
function disableConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);
  const disabledPath = filepath + '.disabled';

  if (fs.existsSync(filepath)) {
    fs.renameSync(filepath, disabledPath);
    console.log(`⏸️  Config disabled: ${domainName}`);
    return true;
  }
  return false;
}

/**
 * Aktifkan kembali config (hapus suffix .disabled)
 */
function enableConfig(domainName) {
  const filename = `${domainName}.conf`;
  const filepath = path.join(NGINX_CONF_DIR, filename);
  const disabledPath = filepath + '.disabled';

  if (fs.existsSync(disabledPath)) {
    fs.renameSync(disabledPath, filepath);
    console.log(`▶️  Config enabled: ${domainName}`);
    return true;
  }
  return false;
}

/**
 * Cek apakah file config ada
 */
function configExists(domainName) {
  const filepath = path.join(NGINX_CONF_DIR, `${domainName}.conf`);
  return fs.existsSync(filepath);
}

/**
 * Generate konfigurasi default server penolak akses IP publik langsung (HTTP & HTTPS)
 * Memastikan tidak ada aplikasi internal yang bocor saat IP diakses langsung.
 */
function generateDefaultCatchAll() {
  const filepath = path.join(NGINX_CONF_DIR, '00-default-block.conf');
  
  const content = `# Auto-generated by Nginx Proxy Panel
# Blokir akses langsung via IP Publik (Port 80 & 443)
# Hanya akses via domain terdaftar dengan Host Header valid yang dilayani

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Tutup koneksi langsung tanpa payload (hemat resource)
    return 444;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    # Gunakan snakeoil cert untuk SSL handshake penolakan
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

    # Tolak koneksi langsung
    return 444;
}
`;

  try {
    fs.writeFileSync(filepath, content, 'utf-8');
    console.log(`🛡️  Default IP block config generated: ${filepath}`);
    return true;
  } catch (err) {
    console.error('Failed to create default IP block config:', err.message);
    return false;
  }
}

/**
 * Generate konfigurasi optimasi global di tingkat HTTP:
 * - Upstream keepalive & WebSocket connection map
 * - Kompresi Gzip otomatis untuk semua jenis konten teks, script, style, json
 * - TCP stack tuning (tcp_nodelay, tcp_nopush, keepalive_timeout)
 * - Proxy buffer size optimal
 */
function generateOptimizationGlobals() {
  const filepath = path.join(NGINX_CONF_DIR, '00-optimization-globals.conf');
  
  const content = `# Auto-generated by Nginx Proxy Panel - Global Performance Optimization
# File ini memuat pengaturan global tingkat http untuk memaksimalkan kecepatan transfer & throughput

# 1. Connection Upgrade Mapping
# Mengizinkan WebSocket berfungsi sempurna dan mengosongkan Connection header untuk HTTP biasa
# agar Upstream Keepalive Connection Pooling bekerja maksimal.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      '';
}

# 2. Gzip Compression Berkecepatan Tinggi
# Mengompresi file teks, HTML, CSS, JavaScript, dan JSON sebelum dikirim ke client
# Mengurangi konsumsi bandwidth hingga 70-80% dan mempercepat loading halaman secara signifikan
gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 5;
gzip_min_length 256;
gzip_types
    application/atom+xml
    application/javascript
    application/json
    application/ld+json
    application/manifest+json
    application/rss+xml
    application/vnd.geo+json
    application/vnd.ms-fontobject
    application/x-font-ttf
    application/x-web-app-manifest+json
    application/xhtml+xml
    application/xml
    font/opentype
    font/truetype
    font/ttf
    image/bmp
    image/svg+xml
    image/x-icon
    text/cache-manifest
    text/css
    text/plain
    text/vcard
    text/vnd.rim.location.xloc
    text/vtt
    text/x-component
    text/x-cross-domain-policy;

# 3. Kernel TCP Stack Optimization
tcp_nopush on;
tcp_nodelay on;
reset_timedout_connection on;
keepalive_timeout 65s;
keepalive_requests 1000;

# 4. Proxy Global Buffering Tuning
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
`;

  try {
    fs.writeFileSync(filepath, content, 'utf-8');
    console.log(`⚡ Performance optimization globals generated: ${filepath}`);
    return true;
  } catch (err) {
    console.error('Failed to create optimization globals config:', err.message);
    return false;
  }
}

/**
 * Regenerasi seluruh file konfigurasi proxy aktif dengan konfigurasi performa tinggi terbaru
 */
async function regenerateAllConfigs() {
  const ProxyModel = require('../models/proxy');
  const systemExec = require('./system_executor');

  // 1. Tulis konfigurasi dasar global
  generateOptimizationGlobals();
  generateDefaultCatchAll();

  // 2. Tulis ulang semua konfigurasi proxy aktif
  const proxies = ProxyModel.getAll();
  let count = 0;
  for (const proxy of proxies) {
    if (proxy.status === 'active') {
      generateConfig(proxy);
      count++;
    } else {
      disableConfig(proxy.domain_name);
    }
  }

  console.log(`🚀 ${count} proxy config(s) regenerated with performance optimizations.`);

  // 3. Reload Nginx jika di server Linux
  const reloadResult = await systemExec.reloadNginx();
  return { success: true, count, reloadResult };
}

module.exports = {
  generateConfig,
  generateDefaultCatchAll,
  generateOptimizationGlobals,
  regenerateAllConfigs,
  removeConfig,
  disableConfig,
  enableConfig,
  configExists,
  NGINX_CONF_DIR
};
